### ISSUE TITLE
Feature request: lncli terminal

### ISSUE THREAD

**Issue by ottosuess** [jamaljsr/polar#220]
idk if it scales to add every possible action to the Actions tab.
i would like an "expert mode" `lncli` terminal that i can open for each lnd node where i can just enter lncli commands like `getinfo` and execute them on the selected lnd.

**Comment by wbobeirne** [comment]
+1, this would be awesome. If you want to do embedded terminals, I highly recommend the [`xterm` package](https://www.npmjs.com/package/xterm). It's the same terminal vscode uses, works great in the browser.

**Comment by jamaljsr** [comment]
I was actually thinking to add API explorers for LND & bitcoind to allow users to interact with all of the RPC endpoints visually instead of using a terminal. I really want this app to be more UI driven and abstract away all of the command line & config file details. My target audience are developers new to building on lightning. They won't have the knowledge and experience of the command line arguments that you guys have. I believe a UI based API explorer would provide a better user experience for newcomers. 

For LND, there are a few [GRPC explorers](https://github.com/grpc-ecosystem/awesome-grpc#gui) available. I haven't dove deep into any of them yet. For bitcoind, I found [btc-rpc-explorer](https://github.com/janoside/btc-rpc-explorer) which looks promising.

Do you guys feel a terminal is still necessary if we have visual explorers with access to all RPC commands?

**Comment by jamaljsr** [comment]
So I spent a bit of time playing with the GRPC explorers and to be quite honest, I don't like the UI of any of them. I feel like I'm going to have to build this myself. Since that would take a fair amount of time and I do want users to have access to all of the lnd/bitcoind RPC, I went ahead and implemented the terminal. @wbobeirne thanks for the tip on xterm, it works great!

I created PR #233  with all the functionality completed. Just need to update unit tests and confirm it works on different OS's. If you have any time, check it out and let me know if there's anything I missed. I'll let the PR sit for a day or two before merging in. You guys can always let me know later if you see any ways to improve it after it's merged. I want to
