### ISSUE TITLE
Sandbox error when running on Arch Linux

### ISSUE THREAD

**Issue by justinmoon** [jamaljsr/polar#227]
Sandbox error when running on Arch Linux:

```
$ yarn dev
yarn run v1.17.3
$ concurrently --kill-others --success first "yarn:dev:*"
$ cross-env BROWSER=none yarn start
$ wait-on http://localhost:3000 && nodemon -I --watch ./electron/ --ext ts --exec electron ./public/dev.js
$ rescripts start
[dev:app] Starting the development server...
[dev:app] 
c[dev:app] Compiled with warnings.
[dev:app] 
[dev:app] ./node_modules/dtrace-provider/dtrace-provider.js
[dev:app] Module not found: Can't resolve './src/build' in '/home/justin/dev/github/polar/node_modules/dtrace-provider'
[dev:app] 
[dev:app] Search for the keywords to learn more about each warning.
[dev:app] To ignore, add // eslint-disable-next-line to the line before.
[dev:app] 
[dev:electron] [nodemon] 1.19.4
[dev:electron] [nodemon] to restart at any time, enter `rs`
[dev:electron] [nodemon] watching dir(s): electron/**/*
[dev:electron] [nodemon] watching extensions: ts
[dev:electron] [nodemon] starting `electron ./public/dev.js`
[dev:electron] [7684:1027/092528.150806:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/justin/dev/github/polar/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
```

I just updated the `dev:electron` command to use `electron --no-sandbox ...` and it works for development at least ...

**Comment by jamaljsr** [comment]
Thanks for the bug report. I havent done any testing on linux yet. I’m curious, can you try running the packaged binary for linux to see if it will run? The downloads are in the github releases https://github.com/jamaljsr/polar/releases/tag/v0.0.1

**Comment by valentinewallace** [comment]
Hey @jamaljsr, I'm running arch linux as well and ran into this error using a packaged binary (`polar-linux-x86_64-v0.0.2.AppImage`) from the downloads page (looks pretty simple to fix?) https://i.imgur.com/ykNx5jB.png

**Comment by jamaljsr** [comment]
Hey @valentinewallace, thanks so much for the screenshots. I plan to spin up an Arch Linux VM and  see if I can fix these issues.

**Comment by jamaljsr** [comment]
Hey @valentinewallace I fixed the issue when running the packaged binary on Linux. The problem was with docker and file permissions. I tested on Arch Linux and Ubuntu and was able to use the app. If you'd like to try it again, download the [v0.0.4](https://github.com/jamaljsr/polar/releases/tag/v0.0.4) release. Please let me know if you run into trouble, 

@justinmoon I was not able to build the app on either Linux VM. Running into c++ compiler errors with the grpc native module. I'll have to spend some more time on this in the future, or hopefully someone with more linux skills 😉 will come along and resolve that problem.
