### ISSUE TITLE
Unable to open the channel  

### ISSUE THREAD

**Issue by tiero** [jamaljsr/polar#252]
**Describe the bug**

**To Reproduce**
1. Create a network of two nodes and start it
2. Click on Deposit funds on alice and then quick mine
3. Click on Outgoing
5. Select Alice and Bob and 250,000 sats 
6. See error "Unable to open the channel  - Cannot convert undefined or null to object"

**Expected behavior**
A channel being opened

**Additional context**
If I login into the terminal the channel seems to be open, but no visual representation

**Comment by jamaljsr** [comment]
Hey @tiero thanks for the bug report. I am aware of this issue and have found the source of it. When deleting a network, there is some internal state that doesn't get cleaned up properly. I have this fixed in my c-lightning branch which I plan to merge before the next release. So this issue will be fixed then.

I will leave this issue open until that PR is merged.

Thanks again

**Comment by jamaljsr** [comment]
The c-lightning branch has been merged into master which includes the fix to this issue. It will be included in the next release.

If you continue to run into this problem in the current release, the workaround is just to close restart Polar. This will clear the internal state that is left over.
