### ISSUE TITLE
More contrast on new UI colors

### ISSUE THREAD

**Issue by grunch** [jamaljsr/polar#275]
This is not a bug report, I'm just wanted to let you know that in some screens the new UI doesn't look good, sometimes it's really difficult to distinguish between nodes box and the background, they have almost the same dark color, it would be great to add more contrast to the app.

besides that, polar is amazing, thanks for it and keep up the hard work.

**Comment by bolatovumar** [comment]
I noticed the reduced contrast as well from the screenshots of the dark theme that I've seen. Probably not too hard to fix and there are tools that can point out color contrast issues.

Also, I'm not sure if the light theme has been removed completely but if it has it might make sense to allow the user to switch between the dark and the light themes.

**Comment by grunch** [comment]
Yes I was looking for somewhere to change back to the light theme but that option is not available

**Comment by jamaljsr** [comment]
Hey all, thank you for the feedback.

Is it only the nodes in the designer that are too dark, or can anyone mention other portions of the UI that is difficult to see?

I can work on the contrast and get a patch release out this week. I’ll also try to squeeze in a toggle to switch between dark & light mode.

**Comment by jamaljsr** [comment]
I just did a quick change locally to lighten the background color of the nodes. Do you think this is enough or should it be lighter?

Before
![image](https://user-images.githubusercontent.com/1356600/72349104-df2f1880-36a9-11ea-8799-fa3ac52ca33f.png)

After
![image](https://user-images.githubusercontent.com/1356600/72349178-05ed4f00-36aa-11ea-998b-577e02147593.png)

I've been using Google's [Material Design Guidelines](https://material.io/design/color/dark-theme.html#properties) as a reference for choosing certain colors. It does discuss contrast but only in the context of text colors on top of background colors. When choosing a background on top of a background, it goes over concepts such as depth and layering. I'm open to further suggestions for improvement so let me know what you all think.

**Comment by grunch** [comment]
Those two screens looks pretty much the same to me, would add more contrast on the nodes :smile:

**Comment by bolatovumar** [comment]
@jamaljsr there are tools which will point out contrast issues. Some examples:

https://contrast-ratio.com/

https://contrastchecker.com

https://webaim.org/resources/contrastchecker/

**Comment by jamaljsr** [comment]
> Those two screens looks pretty much the same to me, would add more contrast on the nodes 😄

Hmmm.. If I make the nodes much lighter, then it won't really be dark mode any more lol. I think bringing back light mode for folks like yourself may be the best solution here.

> @jamaljsr there are tools which will point out contrast issues. Some examples:

Thanks for sharing the links. Tools like these are helpful to optimize contrast between foreground text and background colors. The contrast of the text in the nodes is fine in that regard. 
![image](https://user-images.githubusercontent.com/1356600/72373203-cdfc0100-36d5-11ea-9da6-a4bf42beb789.png)

The issue here is actually the node background color against the canvas background color. I agree that colors in the current release are not easy to distinguish against each other, but there's not much room for adjustment when we are really just showing multiple shades of gray.

**Comment by jamaljsr** [comment]
@grunch  I just merged into master the toggle to switch to light mode. I'm going to package up a v0.2.1 release with just this update. Hope this helps you

**Comment by grunch** [comment]
Awesome thanks buddy
