### ISSUE TITLE
Possible to use Polar as back-end for local app?

### ISSUE THREAD

**Issue by bolatovumar** [jamaljsr/polar#276]
In the README it says:
* Sample app projects/code in different languages (Python, Typescript/JS, Go, C#) showing how to connect to the Lightning/Bitcoin nodes from an external app.

Is it currently possible to use Polar as a back-end for an app that needs to connect to LND/c-lightning? Let's say I want to build https://github.com/Ride-The-Lightning/RTL locally and use Polar as a back-end for testing/development purposes. RTL requires macaroon path (exposed by Polar), LND  config path (not exposed by Polar), LND REST server url (exposed by Polar) and bitcoin.conf file path (not exposed by Polar).

Is this meant to be a supported use case (now or in the future)?

**Comment by jamaljsr** [comment]
I certainly would want Polar to support connecting to the nodes from all apps being built on lightning. I have not done local development of RTL myself, so I was not aware of the paths it requires to connect to nodes. It is fairly trivial to add those paths to the Connect tab in the UI. I'd gladly add these paths, unless someone else does it before I can ;)

**Comment by bolatovumar** [comment]
@jamaljsr alright, i took a quick look and it doesn't look like `lnd.conf` and `bitcoin.conf` exist in the  `.polar` directory which contains all other data. I'm assuming these configuration file must exist somewhere but not sure where they are.

**Comment by jamaljsr** [comment]
@bolatovumar You are correct, Polar does not create these configuration files to disk because it passes all config options as command line arguments. These are specified in the `docker-compose.yml` file for each network and are hard-coded in the [nodeTemplates.ts](https://github.com/jamaljsr/polar/blob/master/src/lib/docker/nodeTemplates.ts) file. I implemented it like this because I imagined that one day I would add some of these config options to the UI and let the user modify them for their use case.

I skimmed through the RTL [authentication](https://github.com/Ride-The-Lightning/RTL/tree/505ba27013bb6d720d36ed9f4052895d24570f65#user-authentication-on-rtl) documentation and it appears to me that the `lndConfPath` is only required when you have RTL & LND installed on the same machine. This is not the case for Polar's docker nodes. Instead, you must set `nodeAuthType=CUSTOM` and `rtlPass=<user defined>` to authenticate. Can you give this a try to see if it works?

**Comment by bolatovumar** [comment]
@jamaljsr looks like none of the options I mentioned are actually required. I raised an issue here and got a response: https://github.com/Ride-The-Lightning/RTL/issues/242.

I will attempt to run RTL with Polar and report back if I succeed or have any issues.

**Comment by jamaljsr** [comment]
Ok cool. Please let me know if you run into any issues.

**Comment by bolatovumar** [comment]
@jamaljsr alright, Polar + RTL works together beautifully. Makes RTL development a breeze.

**Comment by jamaljsr** [comment]
Great to hear! I'll close this issue since no further action is needed.
