### ISSUE TITLE
Bug: Fatal error when opening network from v0.2.1

### ISSUE THREAD

**Issue by wbobeirne** [jamaljsr/polar#314]
**Describe the bug**
Pulled the latest master to get that ZMQ exposure, and opened up the network I had made from `v0.2.1`. I assume there was some change in the data structure that may require some kind of migration, but I haven't dug into it.

**To Reproduce**
Have not reproduced in isolation yet, but here's what I did to get it to happen
1. Run the current release of polar
2. Create a network
3. Run the current master of polar
4. Attempt to open network
5. See error `TypeError: Cannot read property 'image' of undefined`

**Screenshots**

<img width="1012" alt="Screen Shot 2020-03-05 at 1 13 12 AM" src="https://user-images.githubusercontent.com/649992/75957094-e6d79600-5e7e-11ea-8ba9-8ee4c0f01ed0.png">

**Desktop (please complete the following information):**
- OS: macOS 10.14.5
- Polar Version: 0.2.1 / master
- Docker Version: 2.2.0.3.(42716)
- Docker Compose Version: 1.25.4

**Additional context**

**Comment by jamaljsr** [comment]
Hey @wbobeirne, I knew about this issue. The problem is that in master, the package version is still set to 0.2.1. So the migrations will not run on a network that was created with the actual v0.2.1 release build. I usually bump the app version right before a new release instead of in master. I have been manually changing my network file version from `0.2.1` to `0.2.0` in order to trigger the migration. I probably should add a `NODE_ENV != "production"` condition to always run migrations in master.

**Comment by jamaljsr** [comment]
I fixed this in the master branch (https://github.com/jamaljsr/polar/commit/4149e76fdd0ce75285b1097cc9539f490fd5cf47). I didn't feel it necessary to open a PR for a one-liner.

Thanks for the bug report 👍

**Comment by wbobeirne** [comment]
Nice one!
