### ISSUE TITLE
Bug: Unhandled rejection from node request

### ISSUE THREAD

**Issue by wbobeirne** [jamaljsr/polar#315]
**Describe the bug**
When starting a fresh network on the latest master, I got an error while spinning up a network with 2 LND nodes and one Bitcoind node.

**To Reproduce**
1. Create a new network
2. Maybe see `Unhandled Rejection (Error): 14 UNAVAILABLE: failed to connect to all addresses`

**Screenshots**

<img width="1012" alt="Screen Shot 2020-03-05 at 1 22 25 AM" src="https://user-images.githubusercontent.com/649992/75957533-d83dae80-5e7f-11ea-8d1a-00bc548d01d6.png">

Unfortunately not much of a stack trace

**Desktop (please complete the following information):**
- OS: macOS 10.14.5
- Polar Version: master
- Docker Version: 2.2.0.3.(42716)
- Docker Compose Version: 1.25.4

**Comment by jamaljsr** [comment]
I'm not sure what's going on here. I've tried to replicate it locally with no luck. Was this a one time issue or are you able to replicate it? If so, can you share these log files?

App Logs
`~/.polar/logs/main.log` and `~/.polar/logs/renderer.log`

LND Log (just from one node that didn't start)
`~/.polar/networks/<networkId>/volumes/lnd/<node>/logs/bitcoin/regtest/lnd.log`

**Comment by wbobeirne** [comment]
Sorry for the delay, here's everything from around the time it crashed: https://gist.github.com/wbobeirne/eb6875309d3ac15e81286f7a76fc9673

Looks like the noteworthy is carol's last one:
> 2020-03-05 07:24:23.452 [ERR] LTND: Unable to create chain control: unable to connect to bitcoind: -28: Loading block index...

**Comment by jamaljsr** [comment]
No worries. Thanks so much for the logs. They are super helpful. 
_Note: In the timestamps below, please ignore the hour. They are offset because of timezone differences in the docker containers. Focus on the minute & seconds._

I think I see what happened here. We currently give all the nodes 30 seconds to boot up and successfully respond to RPC requests before deeming them as failed. The app polls 10 times in 3 second intervals. In your case, it took 28 seconds for bitcoind to boot up, from [01:19:15](https://gist.github.com/wbobeirne/eb6875309d3ac15e81286f7a76fc9673#file-renderer-log-L11)  to [01:19:43](https://gist.github.com/wbobeirne/eb6875309d3ac15e81286f7a76fc9673#file-renderer-log-L174). During that time, the LND node just kept failing to connect to bitcoind and restarting itself. Eventually it did successfully boot up after 38 secs, with the last log line at [07:19:53](https://gist.github.com/wbobeirne/eb6875309d3ac15e81286f7a76fc9673#file-carol-lnd-log-L82), but this was after Polar already gave up trying and threw an error. 

Were you running this in a VM or had a bunch of other stuff running on your machine at this time? Does it normally take this long for you? On my machine, bitcoind usually boots up in less than 5 secs and LND within 10 secs. I have an i9 with 64Gb of RAM so my machine is probably not ideal for benchmarking. I am not sure how long it takes on most other's machines. I have seen this happen occasionally when I am testing Polar in a Windows VM, but I thought my VM configuration was just screwed up. I don't have any slow bootup issues in my Ubuntu & ArchLinux VMs.

The only solution I can think of for this problem is to increase the retries to 20 (60 second timeout) to better accommodate for longer bootup times. Hopefully, that is enough time for most people. 

> Looks like the noteworthy log is carol's last one:
2020-03-05 07:24:23.452 [ERR] LTND: Unable to create chain control: unable to connect to bitcoind: -28: Loading block index...

I don't think this logged error is related because the timestamp is 5 minutes later at [01:24:12](https://gist.github.com/wbobeirne/eb6875309d3ac15e81286f7a76fc9673#file-renderer-log-L413). It looks like you restarted the network here. This error is normal when the network is first booting up as LND is trying to connect to bitcoind but failing. You can also see this same message at [07:19:21](https://gist.github.com/wbobeirne/eb6875309d3ac15e81286f7a76fc9673#file-carol-lnd-log-L14) and afterwards it eventually connected successfully.

There is a second issue here because you shouldn't ever see that full screen error. That means the app isn't catching it. I actually already fixed this uncaught error in the Log Viewer PR ([here](https://github.com/jamaljsr/polar/pull/316/files#diff-eff17df5836d1b99e1ba4f1692cac9a1R561)) that I was working on. This fix wasn't in master yet when you opened this issue, but it is in master now.

**Comment by wbobeirne** [comment]
Nce detective work! Yeah I'm on a Macbook Pro 2015, and was definitely running a good few things at the same time, so not quite the monster you're packing. I think bumping it up would definitely be reasonable for those of us developing on the go.

Glad to hear the catch is in place though, that was definitely the main issue. I'll close this out since that was merged.

**Comment by jamaljsr** [comment]
@wbobeirne FYI, the timeout increase to 60secs is now in master (https://github.com/jamaljsr/polar/commit/75acb8ffd09930999b5caa3fa5375785343cc843)
