### ISSUE TITLE
Feature Request: Loop

### ISSUE THREAD

**Issue by apotdevin** [jamaljsr/polar#359]
I'm not sure if this is in the scope of this project but would be cool :D

**Is your feature request related to a problem? Please describe.**
I can't test Loop with Polar

**Describe the solution you'd like**
I want the possibility to get a Loop instance running connected to my lightning docker network

**Comment by jamaljsr** [comment]
Hey @apotdevin. I also would love to have Loop support in Polar. Unfortunately, this is not possible today. `loopd` communicates with a backend server to perform the offchain <-> onchain swaps. Lightning Labs maintains these servers for mainnet & testnet. The backend's code is closed source and therefore I cannot make it into a docker image to run inside Polar. My hope is that someday in the future, Lightning Labs is able release a regtest only binary or docker container that Loop developers can use locally. I cannot speak to when or if that will happen, but there has been discussions on the topic. 

Since there isn't anything I can do in Polar right now to implement this, I'm going to close this issue. If this ever becomes a possibility, trust me, I will implement it immediately. I want this functionality for myself as well.

**Comment by apotdevin** [comment]
Thanks for the info! Yeah wasn't to sure if it was even possible so thanks for the clarification. Awesome to hear :) would definitely simplify a lot of integration testing.
