### ISSUE TITLE
Feature Request: Rename nodes

### ISSUE THREAD

**Issue by kibotrel** [jamaljsr/polar#388]
It would be nice if we could rename each individual node. Sometimes, Alice, Bob and Carol... are too vague for practical usage.

**Comment by jamaljsr** [comment]
I agree, this would be a good feature to implement. I don't think there are any downsides to renaming a node. It would just need to update the value stored in the network and restart the node in order for the `alias` to be updated.

Thanks for the feedback.

**Comment by kzu** [comment]
Would be totally awesome to be able to name nodes. This would make also for a more realistic representation when discussing and brainstorming on the topology things might result in in actual production.

**Comment by Marvel-Ib** [comment]
hi, @jamaljsr  I wanted to know if this is still okay to work on.  Not sure i can handle it but I would definitely love to try.

**Comment by jamaljsr** [comment]
Thanks for asking. Yes, you can work on it. I am not aware of anyone currently implementing this feature.

**Comment by umarluqman** [comment]
I will try to work on this.

I just looked into the Redux store and highlighted the value or key that will need to be changed when the user change the node name. Just to confirm with you, am I missing something?

<img width="542" alt="Screenshot at Jan 17 16-21-50" src="https://github.com/jamaljsr/polar/assets/25649761/11d53acc-6d13-4abf-85fb-477b713f2c14">

<img width="474" alt="Screenshot at Jan 17 16-23-51" src="https://github.com/jamaljsr/polar/assets/25649761/cd085a2b-1da7-4748-9724-f43ff4567bc6">

**Comment by jamaljsr** [comment]
Hey @umarluqman, thanks for taking a shot at this feature. 

The data in the store that you found are actually all derived from the node names in the network object. This is the primary source for the name.

![image](https://github.com/jamaljsr/polar/assets/1356600/61834959-58db-49f1-ab46-ed94eec7606a)

Once this name is changed, the `lightning` store will automatically begin using the new name when it fetches data from the node's APIs. However, it may be cleaner to rename the keys in there to avoid needing to refetch data again. 

The data in the `designer` store couple possibly be regenerated using the functions in [chart.ts](https://github.com/jamaljsr/polar/blob/master/src/utils/chart.ts) but I'm not 100% certain. You may need to create a new function to specifically do the rename.

The biggest challenge I can think of is handling the renaming of the node directory that's stored on the host machine's file system, like `~/.polar/networks/1/volumes/lnd/alice/`. The node must be stopped in order to rename this dir. It may be simpler to just require the whole network to be stopped in order to rename a node so you don't have to deal with processes holding files open, which would prevent renaming the parent dir.

Let me know if you have any more questions.

**Comment by umarluqman** [comment]
Thanks for the explanation, I have two things in mind. 

1. If we were stopping the whole network probably we can have a button - Rename Node, then when the user click it, it will show a confirmation modal as for the network will be stop for the nodes to be renamed.  If use click Yes, then all the node will become an input with the existing node name as the value and also beside the Rename Node button, there will be two more buttons - X and ✓ button.

After the user rename the node, they can click the ✓ button and X to cancel renaming the node. Probably theres' better UX for this, I'm just putting it out here.

2. Secondly, I was thinking if we could have name node configure during the node creation setup. This one is simpler I guess. This is the proposed design.

<img width="893" alt="Screenshot at Jan 23 08-13-40" src="https://github.com/jamaljsr/polar/assets/25649761/0297572e-f42c-4eaf-8baf-170fcf0fe984">

We can have a plus icon button, to insert multiple node names instead of specifying the node count. there will be a placeholder - Node name for better UX

**Comment by Jem256** [comment]
Hey @umarluqman are you still working on this?

**Comment by Jem256** [comment]
Hey @jamaljsr I'd like to handle this if that's okay

**Comment by jamaljsr** [comment]
Go for it 👍

**Comment by Jem256** [comment]
Hey @jamaljsr I would appreciate some help. I wrote a rename function to update the network store which updates the name of the node as below "Alic" 
![Screenshot from 2024-03-05 10-06-05](https://github.com/jamaljsr/polar/assets/72874905/e92907d4-adee-4141-9cf5-04a1d18cc36f)

However, the designer store doesn't seem to update with this information as it remains 'alice' 
![Screenshot from 2024-03-05 10-06-54](https://github.com/jamaljsr/polar/assets/72874905/a1e32cf2-4967-4119-a1c0-62af80379424)

The `syncChart` function in the designer store doesn't seem to do the update and I am not sure whether i should be using the `updateChartFromNodes` method from chart.ts

**Comment by Jem256** [comment]
Hey @jamaljsr I would like some clarification on how the `onPortPositionChange` function in the designer is receiving its props because I am encountering this error when i leave the network view screen and return to it after a rename 
![Screenshot from 2024-03-07 10-51-27](https://github.com/jamaljsr/polar/assets/72874905/473c75c2-5175-4e76-8c9c-a25db25e35c4)

the network object also has this error that I am having difficulty in tracing. This also affects the retrieval of the node info. 
![Screenshot from 2024-03-07 10-50-54](https://github.com/jamaljsr/polar/assets/72874905/30e03385-a140-40ca-8916-e9a6e9f7808f)

**Comment by jamaljsr** [comment]
Hey @Jem256, can you push the code that exhibits this behavior so I can reproduce it and investigate.
