### ISSUE TITLE
Bug: some nodes keep restarting

### ISSUE THREAD

**Issue by ramontayag** [jamaljsr/polar#464]
**Describe the bug**
Some nodes keep restarting, sometimes I'm unable to sync the whole polar graph at all

**To Reproduce**
1. Create a network with 4 LND, 3 c-lightning, 1 backend (I've seen it break with less)
2. Start network
3. See that not all start properly

**Expected behavior**
Expected them to start properly

**Screenshots**
Here's a screencast:
https://user-images.githubusercontent.com/25332/119228639-79c52480-bb46-11eb-9a18-d7104551a83e.mp4

**Desktop (please complete the following information):**
- OS: MacOS Big Sur M1
- Polar Version: 1.20
- Docker Version: 3.3.3 (64133)
- Docker Compose Version: 1.12.2

**Comment by jamaljsr** [comment]
Hey @ramontayag thanks for the screencast, that was very helpful. It looks like docker is taking a long time to start up all these nodes. It took 50 seconds for Polar to connect to the bitcoind node successfully, while on my machine this only takes 8 seconds. The c-lightning nodes were online in ~60 seconds. Polar stopped trying to connect to the LND nodes after ~90 seconds. Once Polar stops trying to connect, it gets pretty difficult to resync the UI with the underlying docker containers. You have to try to restart them one by one.

It looks like you're running on an M1 and a compatible docker version. I would think your startup should be much faster than my machine. I don't have an M1 to test on, but my hunch is the docker startup time is what's causing the issues in Polar. Can you repeat what you did in the video, but after waiting for the nodes to either startup or for Polar to timeout, can you run `docker-compose -f ~/.polar/networks/1/docker-compose.yml logs > polar-startup.log`? Then upload the `polar-startup.log` file to this issue. This way we can analyze the timestamps to confirm the this to be the root of the problem.

**Comment by ramontayag** [comment]
Thanks for the reply @jamaljsr!

Ok here it is: 
[polar-startup4.log](https://github.com/jamaljsr/polar/files/6536070/polar-startup4.log)

Gathered more data: I spun up a network on a Macbook Air ~2015 model (Intel chip), and had no problems.

**Comment by jamaljsr** [comment]
Did you attach the log file of a network that failed to start up properly? Based on the timestamps, it looks like all of the nodes were up in ~60 secs. The bitcoind node started in 15 secs. This doesn't appear to be the same behavior displayed in the initial screencast you posted.

**Comment by ramontayag** [comment]
Hmm yes, they no longer restart in docker, but most nodes appear red in Polar:

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/25332/120057267-6ea55380-c074-11eb-8e6b-433dddf89963.png">

They're also unresponsive. I tried to open a channel after forcing one of them to restart (so I have two nodes that are green), but the open channel dialog is just hangs there.

Here are two files.

1) taken a few minutes after start up while most nodes were still red but docker said they were running
[polar-startup5.log](https://github.com/jamaljsr/polar/files/6564011/polar-startup5.log)

2) taken after I restarted dave, and tried to create a channel between dave and erin
[polar-startup6.log](https://github.com/jamaljsr/polar/files/6564012/polar-startup6.log)

**Comment by jamaljsr** [comment]
Ok, thanks for these logs. I see that the problem is indeed slow Docker performance. Polar currently waits 60 seconds for the nodes to respond to `getinfo` requests. After the 60s it will display the red failed status. If you get the failed startup on nodes then the UI will be out of sync with the docker containers and some operations will not behave as expected. This is why opening a channel isn't working as expected.

Based on the timestamps from your logs, most of the nodes are taking over 60s to completely start up. Here are the times for each of your nodes:

| node | start | shutdown | restart | online | total secs | 
| - | - | - | - | - | - |
| backend1 | 46:53 |  |  | 46:59 | 6 |
| alice | 46:47 | 46:53 | 47:38 | 47:58 | 71 |
| bob | 46:50 | 46:52 | 47:24 | 47:55 | 65 |
| carol | 46:48 | 46:52 | 47:28 | 47:58 | 70 |
| dave | 46:47 | 46:53 | 47:37 | 48:06 | 79 |
| erin | 46:51 | 46:52 | 47:22 | 47:46 | 55 |

The LN nodes will always fail to startup the first time because `bitcoind` isn't online, but Docker will automatically restart them. Looking at `alice` you can see that it took 6s for the first startup to fail. Then docker took 45s to restart the container, then it took 20s for LND to fully start up, for a total of 71s. You can also see that `erin` took 55s to startup which is why it is green in your screenshot.

Now let's compare your times to what I get on my 2019 i9 MacBook:
[polar-startup-i9.log](https://github.com/jamaljsr/polar/files/6565151/polar-startup-i9.log)

| node | start | shutdown | restart | online | total secs | 
| - | - | - | - | - | - |
| backend1 | 25:03 |  |  | 25:16 | 12 |
| alice | 25:03 | 25:03 | 25:04 | 25:10 | 7 |
| bob | 25:03 | 25:03 | 25:04 | 25:09 | 6 |
| carol | 25:03 | 25:03 | 25:04 | 25:09 | 6 |
| dave | 25:03 | 25:03 | 25:04 | 25:10 | 7 |
| erin | 25:03 | 25:03 | 25:04 | 25:10 | 7 |

On my machine, `alice` took less than 1s for the first startup to fail. Then Docker only waited 1s to restart the container, then LND took just 6s to completely startup.

It looks like Docker on the M1 is running much slower that on my Intel machine. I'm not sure if there is emulation going on because the images that Polar uses are x86. 

This is the root cause of the trouble your facing. The best solution I have for now is to simply extend the timeout from 60s to 120s so that Polar waits longer for the nodes to come online. Once Polar recognizes them as online then you should be able to interact with them normally. You may just experience slow performance since it appears the Docker is ~10x slower on the M1 for some reason. I'll have to dive deeper into this once I get my hands on an M1 later this year.

I'll create a PR to extend the timeout which will be available in an upcoming release. I'm shooting to ship it in the next week.
