### ISSUE TITLE
Feature Request: LND v0.13.x images

### ISSUE THREAD

**Issue by wbobeirne** [jamaljsr/polar#480]
O sweet Polar gods, can you bestow upon us fresh docker images for v0.13.0, and v0.13.1? I'm trying to find a regression somewhere and this would be amazingly useful. Thanks!

**Comment by jamaljsr** [comment]
Lol.. sup WOB! What you over there cookin up, on the low?

We do have those images in Polar. Just hit the "Show All Versions" toggle, then scroll to the bottom and click "Check for new Node Versions". 

![image](https://user-images.githubusercontent.com/1356600/127171932-6f5c970f-52a1-4eb9-8831-735eb46c557e.png)

I have to improve this experience because this is a question I get pretty often. I was trying to steer away from automatica updates because "muh privacy". Im realizing that an occasional phone home to github.com may not be such a bad trade-off with the boost in convenience, especially if it's opt-in.

**Comment by wbobeirne** [comment]
D'oh, shoulda known. In my opinion that's a very reasonable trade-off, but I appreciate that you took that into account. I leave it up to you to decide what the best path forward is, but this issue is clearly bupkis.
