### ISSUE TITLE
Connecting to electrs 

### ISSUE THREAD

**Issue by ConorOkus** [jamaljsr/polar#618]
Is it possible to connect an [Esplora](https://github.com/blockstream/electrs) instance to Polar?

**Comment by jamaljsr** [comment]
I haven't tried it myself but you should be able to run Electrs using a bitcoind node in Polar. It looks like you have to pass in the `--daemon-dir` flag which should point to the bitcoin data dir. With Polar nodes, this data is stored on your machine in the `~/.polar/networks/1/volumes/bitcoind/backend1/regtest/` dir. You may need to change the number `1` in the path since this corresponds to the index of the network in Polar. 

Please let me know if you get it working. I'm curious to know.

**Comment by ConorOkus** [comment]
Okay that nearly worked but getting the following error:

`WARN - reconnecting to bitcoind: failed to read cookie from "/Users/cokus/.polar/networks/1/volumes/bitcoind/regtest/.cookie"`

Does Polar support cookie-based auth at all?

**Comment by ConorOkus** [comment]
Got it working! Extremely helpful for mobile development. Thanks
