### ISSUE TITLE
Enable keysend by default in lnd

### ISSUE THREAD

**Issue by benthecarman** [jamaljsr/polar#631]
I don't know why lnd doesn't do this yet but would be nice to have polar at least do this.

**Comment by jamaljsr** [comment]
You can configure Polar so that your LND nodes always have this flag set. Just go to Manage Images, click on Edit for the LND image you want to change, then modify the command line flags. 

![image](https://user-images.githubusercontent.com/1356600/203467387-7dad1dc5-c395-4750-8786-81f8c4d0cf68.png)
 
In https://github.com/jamaljsr/polar/issues/479#issuecomment-887583254 I've given a longer explanation on why we don't turn on keysend by default Polar.

**Comment by amovfx** [comment]
Yea this is what I'm doing too and it works well.
