### ISSUE TITLE
Bug: incorrect big amount when depositing funds on Eclair 

### ISSUE THREAD

**Issue by louneskmt** [jamaljsr/polar#652]
**Describe the bug**
When depositing 1M sats to an Eclair node (default value), several billions seem to be credited.

**To Reproduce**
1. Add an Eclair node
2. Deposit some sats from the `Actions` tab (here 1M)
3. Wait a bit and check the deposited amount on the `Info` tab
4. See that the amount isn't correct and way too big

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/38882571/211317199-ac72c39a-7904-4ee3-a2f0-748cafb6badd.png)
![image](https://user-images.githubusercontent.com/38882571/211317231-da28ff85-1004-4aab-9fb7-18074ff76177.png)

**Desktop:**
- OS: macOS Ventura 13.0 
- Polar Version: v1.4.0
- Docker Version: v20.10.21
- Docker Compose Version: v2.12.2

**Comment by jamaljsr** [comment]
This is a side-effect  of how Eclair works under the covers. It doesn't have a built-in onchain wallet. Instead, it uses the wallet of the connected bitcoind node. So when you mine blocks on the bitcoind node, the block rewards will also show up as a balance on the connected Eclair node. There isn't much Polar can do about this as it's just how Eclair was designed.

As somewhat of a workaround, it you want the Eclair node's balance to be exactly what you deposit, is to add a separate bitcoin node for Eclair. For example, create a network with 2 Eclair and 2 Bitcoin Core nodes. Deposit 1M sats into the alice node and you will see the high balance as you've mentioned. Now deposit 1M sats into the bob node. You'll notice the bob now has exactly 1M sats, but alice's balance has also increased due to the block rewards of the first bitcoin node.
