### ISSUE TITLE
data from docker container's gets erased after restarting the system 

### ISSUE THREAD

**Issue by AtmegaBuzz** [jamaljsr/polar#678]
**Describe the bug**
I ran 2 LN core nodes and installed some packages and software for testing but after restarting my OS and running the containers again all the configurations get deleted. it's like starting new docker instance. is it because the volume isn't setup. 

**Desktop (please complete the following information):**
- OS: Pop Os
- Polar Version: [e.g. 0.2.0]
- Docker Version: [e.g. 19.03.1]
- Docker Compose Version: [e.g. 1.24.1]

**Additional context**

**Comment by jamaljsr** [comment]
This is expected behavior. The docker containers aren't fully persistent across restarts. Polar uses volumes to mount the `/home/clightning/.lightning/` data dir inside the container to `~/.polar/networks/2/volumes/c-lightning/bob/lightningd/` on your host OS. Any other changes made inside the container will not be persisted across restarts.

If you want to make persistent changes to the containers, you'd need to create your own [custom docker image](https://github.com/jamaljsr/polar/blob/master/docs/custom-nodes.md) with the modifications you want. You can still use Polar to manage and connect to the nodes using your custom image.

**Comment by AtmegaBuzz** [comment]
ok now i got it, Thanks @jamaljsr  :)
