### ISSUE TITLE
Feature Request: Rename node

### ISSUE THREAD

**Issue by SeverinAlexB** [jamaljsr/polar#739]
**Is your feature request related to a problem? Please describe.**

I have 5 bitcoin nodes with different configuration which I confuse all the time.

**Describe the solution you'd like**

PLEASE let me rename the nodes so I can identify them!

**Additional context**

<img width="879" alt="CleanShot 2023-06-28 at 16 34 45@2x" src="https://github.com/jamaljsr/polar/assets/8782386/90d386e9-b178-4842-ba95-a2fb8cdd3bb5">

**Comment by jamaljsr** [comment]
I fully agree that this would be a great feature to add. There were other contributors that expressed interest in implementing this but there haven't been any PRs submitted yet. I may end up tackling this when time permits as I have wanted this myself in the past.

This was originally requested in https://github.com/jamaljsr/polar/issues/388 so I am going to close this issue so that there aren't any duplicates. I'll keep that one open.
