### ISSUE TITLE
Bug: Cannot open app on MacOS 'macOS cannot verify that this app is free from malware'

### ISSUE THREAD

**Issue by raweber42** [jamaljsr/polar#840]
**Describe the bug**
When downloading Polar 2.0.0 or 2.0.1, I cannot open the app on my MacBook without using an unsecure workaround.

**To Reproduce**
1. Use a macBook with the latest OS
2. Download Polar 2.0.0 via website/Github
3. Try to open it

**Expected behavior**
I should be able to open the app without any warnings.

**Screenshots**

**Desktop (please complete the following information):**
- OS: Sonoma 14.1
- Polar Version: 2.0.0
- Docker Version: v24.0.6
- Docker Compose Version: 2.22.0

**Additional context**
Error message shown: 'macOS cannot verify that this app is free from malware'

**Comment by jamaljsr** [comment]
Yes, this is a known issue that is due to there being high costs for signing certificates from Apple and Microsoft to bypass these warnings on their OS's. Since this app is MIT licensed and generates no income, I do not have any plans on covering the cost to buy these certs annually myself.

To work around this, you can do one of two things: 
1. Open Applications in Finder -> right-click Polar.app -> Open -> Cancel -> right-click Polar.app -> Open
2. Build the app from source code. See the [Packaging the production binary](https://github.com/jamaljsr/polar/blob/master/CONTRIBUTING.md#packaging-the-production-binary) docs

**Comment by 634-5789** [comment]
Method 1 with right-clicks is not working in macOS Sequoia 15.1.1.
